Listen 82
FcgidMaxRequestLen 1073741824

<VirtualHost *:82>
    AddDefaultCharset UTF-8
    ScriptAlias / /opt/rt4/sbin/rt-server.fcgi/
    DocumentRoot "/opt/rt4/share/html"
    <Location />
        Options +ExecCGI
        AddHandler fcgid-script fcgi
        Require all granted
    </Location>
</VirtualHost>
